### ISSUE TITLE
it does not work for me when i use neobundle!

### ISSUE THREAD

**Issue by wsdjeg** [JalaiAmitahl/maven-compiler.vim#3]
i think the pom.vim has been soursed even though i do not cp the dir into ~/.vim
because when i open a file named pom.xml
the &ft=pom
but when i set the commend it does not work 
i am using https://github.com/scrooloose/nerdcommenter
this plugin works well for xml jsp html and any other filetype
but it does not works when change the ft = pom

**Comment by JalaiAmitahl** [comment]
I'm not sure what exactly you are asking for here...

Could you provide a bit more information please?

**Comment by wsdjeg** [comment]
thank you for your reply.
i mean when i open a file named pom.xml
i can not use nerdcommenter 
but in other  xml file the nerdcommenter works well
it can note the current line by add

**Comment by wsdjeg** [comment]
in pom.xml
it only add 
/\* current line */

**Comment by JalaiAmitahl** [comment]
I'll look into what I can do to resolve this.  Thanks. :)

**Comment by wsdjeg** [comment]
thank you very much

**Comment by wsdjeg** [comment]
sorry it is nerdcommenter's feature,so close it ,thank you
